#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

BIN_NAME="promtail"
OS="linux"
ARCH="amd64"

REPO="grafana/loki"
TARBALL_URL=$(curl --silent "https://api.github.com/repos/${REPO}/releases/latest" | jq -r .tarball_url)
VERSION=$(grep -o '[^/v]*$' <<< "${TARBALL_URL}")
FILE_NAME="${BIN_NAME}-${OS}-${ARCH}.zip"
DOWNLOAD_URL="https://github.com/${REPO}/releases/download/v${VERSION}/${FILE_NAME}"

WORKDIR="$(mktemp -d -t ${BIN_NAME}.XXXXXXXXX)"

TMP_FILE="${WORKDIR}/${FILE_NAME}"

INSTALL_PATH="/usr/local/bin/${BIN_NAME}"

function finish {
  rm -rf "${WORKDIR}"
}

trap finish EXIT

curl --silent -Lo "${TMP_FILE}" "${DOWNLOAD_URL}"

unzip -q "${TMP_FILE}" -d "${WORKDIR}"

install "${WORKDIR}/${BIN_NAME}-${OS}-${ARCH}" "${INSTALL_PATH}"
